"""Turn results/tone_level_map.json into the numbers the firmware needs.

Given the fitted SPL = a*level_db + b per frequency (dB SPL -- this tool
refuses uncalibrated dBFS files), it emits:

1. `CONFIG_HAVEN_TONE_FULL_SCALE_DB` -- the commanded level that should map
   to 0 dBFS so that a commanded 85 produces <= 85 dB SPL at the WORST
   measured frequency/seal. Today that Kconfig is 85 by definition (nominal);
   the measured value replaces it.
2. A per-frequency offset table (C header snippet) for a later firmware
   change that corrects each LDL frequency individually.

Everything is emitted with provenance comments (date, fixture, mic cal) so a
number in a header can always be traced back to a measurement.

    python3 firmware_constants.py results/tone_level_map.json [--margin-db 2] > haven_tone_cal.h
"""
import argparse
import json
import sys

from constants import TONE_LEVEL_MAX_DB


def derive(results, margin_db=2.0, ceiling_dbspl=TONE_LEVEL_MAX_DB):
    """Returns dict with per-frequency offsets and the full-scale setting.

    Model: measured SPL(level) = a*level + b. If the firmware maps level_db to
    full-scale as gain = 10^((level - FS)/20), then changing FS by d shifts
    every SPL by -d. We want SPL(85) <= ceiling - margin at every frequency:
      needed shift d_f = SPL_f(85) - (ceiling - margin)      (per frequency)
      FS_new = FS_old + max_f(d_f)                            (global, conservative)
      offset_f = max_f(d_f) - d_f                             (per-frequency correction,
                                                              >= 0, applied as extra gain
                                                              at frequencies that were quieter)
    """
    prov = results.get("provenance", {})
    if prov.get("uncalibrated") or prov.get("simulated_audio"):
        raise SystemExit("refusing: this map is " + ("SIMULATED" if prov.get("simulated_audio") else "uncalibrated (dBFS)")
                         + " -- firmware constants must come from a calibrated measurement")
    fs_old = float(prov.get("tone_full_scale_db", TONE_LEVEL_MAX_DB))
    rows = {}
    for f0, r in results["per_frequency"].items():
        if r["fit"]["unit"] != "dB SPL":
            raise SystemExit(f"refusing: {f0} Hz fit is in {r['fit']['unit']}, not dB SPL")
        a, b = r["fit"]["slope"], r["fit"]["offset"]
        spl_at_cap = a * ceiling_dbspl + b
        rows[int(f0)] = {"slope": a, "offset": b, "spl_at_85": spl_at_cap,
                         "needed_shift_db": spl_at_cap - (ceiling_dbspl - margin_db),
                         "slope_ok": r["fit"]["slope_ok"]}
    worst_shift = max(v["needed_shift_db"] for v in rows.values())
    for v in rows.values():
        v["per_freq_offset_db"] = worst_shift - v["needed_shift_db"]
    return {"full_scale_db_old": fs_old, "full_scale_db_new": fs_old + worst_shift,
            "worst_shift_db": worst_shift, "margin_db": margin_db, "ceiling_dbspl": ceiling_dbspl,
            "per_frequency": rows, "any_slope_bad": any(not v["slope_ok"] for v in rows.values())}


def render_header(d, prov):
    lines = [
        "/* Generated by tools/calibration/firmware_constants.py -- DO NOT EDIT BY HAND.",
        f" * date: {prov.get('date')}",
        f" * fixture: {prov.get('fixture')}",
        f" * mic cal: {json.dumps(prov.get('mic_cal'))}",
        f" * model: SPL = slope*level_db + offset per LDL frequency; ceiling {d['ceiling_dbspl']:.0f} dB SPL, margin {d['margin_db']:.1f} dB",
        " */",
        "#ifndef HAVEN_TONE_CAL_H_",
        "#define HAVEN_TONE_CAL_H_",
        "",
        f"/* Kconfig: set CONFIG_HAVEN_TONE_FULL_SCALE_DB={round(d['full_scale_db_new'])} (was {d['full_scale_db_old']:.0f}). */",
        f"#define HAVEN_TONE_FULL_SCALE_DB_MEASURED {d['full_scale_db_new']:.2f}f",
        "",
        "/* Per-frequency extra gain (dB, >= 0) so every LDL tone hits the same SPL for the same level_db. */",
        "struct haven_tone_cal_point { float f0_hz; float offset_db; float slope; };",
        "static const struct haven_tone_cal_point haven_tone_cal[] = {",
    ]
    for f0 in sorted(d["per_frequency"]):
        v = d["per_frequency"][f0]
        flag = "" if v["slope_ok"] else "  /* SLOPE != 1: fix firmware before using */"
        lines.append(f"\t{{ {f0:.1f}f, {v['per_freq_offset_db']:.2f}f, {v['slope']:.3f}f }},{flag}")
    lines += ["};", "", "#endif /* HAVEN_TONE_CAL_H_ */"]
    if d["any_slope_bad"]:
        lines.insert(0, "#error \"tone_level_map slope != 1 at some frequency: the level_db->gain conversion is wrong in firmware; do not ship this table\"")
    return "\n".join(lines) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("map_json")
    p.add_argument("--margin-db", type=float, default=2.0, help="keep measured ceiling this far under 85 dB SPL (measurement uncertainty)")
    args = p.parse_args(argv)
    with open(args.map_json) as f:
        results = json.load(f)
    d = derive(results, args.margin_db)
    sys.stdout.write(render_header(d, results.get("provenance", {})))
    return 0


if __name__ == "__main__":
    sys.exit(main())
