#!/usr/bin/env python3
"""What can and cannot be learned about the FastDSP master-limiter slot from
the data we have.

Goal: make the limiter (slot 9 of upstream's FastDSP program) a configurable
third safety layer. That needs the meaning of its five parameter words.

Evidence available:
  1. upstream's three parameter banks (open-earable-2 Lark-fdsp.c), slot 9;
  2. upstream's `dsp noise_gate` shell command, which writes the EXPANDER
     slot (5) as: p0 = threshold | 0xC80, p1 = gain_min | 0xD00,
     p2 = gain_max, p3 = attack, p4 = release | 0x80000000 -- i.e. for the
     dynamics blocks the LOW bits of some words are opcode/flag fields and
     the value lives in the upper bits;
  3. ADI's Lark SDK (read-only reference): it has NO per-block parameter
     helpers for the FastDSP -- blocks are generated by Lark Studio and the
     SDK only exposes program/bank load, bank switch, safeload and rate.
     There is nothing to decode the limiter against.

What the data says (run this file):
  * slot 9, all three banks: p0 = 0xC8000000, p1..p4 = 0.
  * every other dynamics/routing slot also carries a non-coefficient control
    word in p0 (expander 0x08000C80, volume 0x17F00000, mute 0xC9F00000,
    mixer 0xD1A40000) -- so p0 of slot 9 is a control word, not a Q5.27
    threshold, and a limiter with p1..p4 = 0 has no attack/release/ratio
    values we can point at.
  * the program word for slot 9 (0x04800000) has a different shape from the
    biquad/dynamics words (0x00B24800, 0x01005000, ...).

Conclusion -- CANNOT be decoded from this data: a single sample with only a
control word set, no block documentation, and no SDK helper is not enough to
know which bits are the threshold, or even whether this block is configured
as a limiter at all (it may be a pass-through the designer left in). Writing
guessed words into it could silently disable whatever it does now. The
honest, verified alternative for a hardware output ceiling is the DAC volume
register, whose encoding the Lark SDK documents exactly
(`adi_lark_dac_set_volume`: "output dB = 24 - 0.375 * volume; 0xFF mutes"),
and which sits AFTER the FastDSP in the signal chain. That is what the
firmware implements (CONFIG_HAVEN_OUTPUT_CEILING_DB).

To make the FastDSP limiter itself configurable, someone with Lark Studio
must open upstream's program (or rebuild it), read the limiter block's
parameter layout from the tool, and record it here.
"""
FDSP_PROGRAM = [0x00824800, 0x00B24800, 0x00B24800, 0x00B24800, 0x00B24800, 0x01005000,
                0x01804800, 0x01805200, 0x01C04800, 0x04800000, 0x00000000, 0x00000000]
# bank[param][slot] for slots 5..9 only, all three banks are identical for slot 9
BANK1 = [
    [0x07FE81DE, 0x0790CF27, 0x006DC082, 0x04097BA8, 0x083C4385, 0x08000C80, 0x17F00000, 0xC9F00000, 0xD1A40000, 0xC8000000, 0, 0],
    [0xF00A380A, 0xF1435005, 0x00DB8104, 0xF806CE83, 0xF03C9B90, 0x04000D00, 0x00000000, 0x00000000, 0xFD000000, 0x00000000, 0, 0],
    [0x07F74A0F, 0x07463618, 0x006DC082, 0x03EFFE9E, 0x078BFEC9, 0x00010000, 0x02014700, 0x00014700, 0x08000000, 0x00000000, 0, 0],
    [0x0FF5C5FD, 0x0EBCAFFB, 0x0B15CAC3, 0x0FE8B753, 0x0FC36470, 0x00004000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0, 0],
    [0xF80A321A, 0xF928FAC0, 0xFB333334, 0xF816B773, 0xF837BDB2, 0x82180000, 0x04000000, 0x00000000, 0x00000000, 0x00000000, 0, 0],
]
SLOTS = {5: "expander", 6: "volume", 7: "mute", 8: "mixer", 9: "limiter_master"}


def q527(w):
    return ((w - (1 << 32)) if w & 0x80000000 else w) / (1 << 27)


def main():
    print("slot  name             program_word  p0..p4 (hex)                                             p0 as Q5.27")
    for s, name in SLOTS.items():
        words = [BANK1[p][s] for p in range(5)]
        print(f"{s:>4}  {name:16s} 0x{FDSP_PROGRAM[s]:08X}    {' '.join(f'{w:08X}' for w in words)}   {q527(words[0]):+.3f}")
    print("\nExpander shell-command layout (upstream ADAU1860.cpp cmd_dsp_noise_gate):")
    print("  p0 = threshold | 0xC80   p1 = gain_min | 0xD00   p2 = gain_max   p3 = attack   p4 = release | 0x80000000")
    print("  -> low bits of p0/p1 and bit 31 of p4 are flag/opcode fields; values live in the remaining bits.")
    print("\nSlot 9 has only a control word (0xC8000000) and zeros: threshold/attack/release are not present.")
    print("VERDICT: limiter parameters cannot be decoded from this data; see module docstring.")
    print("\nVerified alternative -- DAC volume register (Lark SDK adi_lark_dac_set_volume): dB = 24 - 0.375 * code, 0xFF = mute")
    for db in (24, 0, -6, -12, -20, -60):
        code = round((24 - db) / 0.375)
        print(f"  ceiling {db:+4d} dB -> DAC_VOL0 code {code:3d} (0x{code:02X})")


if __name__ == "__main__":
    main()
